import type { User, DriveRoots } from '../types'

declare global { interface Window { google?: { accounts: { oauth2: { initTokenClient: (arg: { client_id: string; scope: string; callback: (response: { access_token?: string; error?: string }) => void }) => { requestAccessToken: (arg: { prompt: string }) => void } } } } } }
const DRIVE_SCOPE = 'openid email profile https://www.googleapis.com/auth/drive.file'
let accessToken = ''
export const hasGoogleConfig = () => Boolean(import.meta.env.VITE_GOOGLE_CLIENT_ID)
export function loadGoogle() { return new Promise<void>((resolve, reject) => { if (window.google) return resolve(); const s = document.createElement('script'); s.src = 'https://accounts.google.com/gsi/client'; s.async = true; s.onload = () => resolve(); s.onerror = () => reject(new Error('Google sign-in could not load')); document.head.appendChild(s) }) }
export async function signIn(): Promise<User> { await loadGoogle(); const token = await new Promise<string>((resolve, reject) => { const c = window.google!.accounts.oauth2.initTokenClient({ client_id: import.meta.env.VITE_GOOGLE_CLIENT_ID, scope: DRIVE_SCOPE, callback: r => r.access_token ? resolve(r.access_token) : reject(new Error(r.error || 'Permission denied')) }); c.requestAccessToken({ prompt: accessToken ? '' : 'consent' }) }); accessToken = token; const profile = await fetch('https://www.googleapis.com/oauth2/v3/userinfo', { headers: { Authorization: `Bearer ${token}` } }).then(r => r.ok ? r.json() : Promise.reject(new Error('Could not get Google profile'))); return { email: profile.email, name: profile.name, picture: profile.picture } }
export function signOut() { accessToken = '' }
export const isConnected = () => Boolean(accessToken)
async function drive(path: string, init: RequestInit = {}) { if (!accessToken) throw new Error('Google Drive connection expired. Sign in again.'); const r = await fetch(`https://www.googleapis.com/drive/v3/${path}`, { ...init, headers: { Authorization: `Bearer ${accessToken}`, ...(init.headers || {}) } }); if (!r.ok) throw new Error(`Google Drive error (${r.status})`); return r }
async function findOrCreateFolder(name: string, parent?: string) { const q = [`name='${name.replace(/'/g, "\\'")}'`, "mimeType='application/vnd.google-apps.folder'", 'trashed=false', parent ? `'${parent}' in parents` : ''].filter(Boolean).join(' and '); const found = await drive(`files?q=${encodeURIComponent(q)}&fields=files(id)`).then(r => r.json()); if (found.files[0]) return found.files[0].id; const meta = { name, mimeType: 'application/vnd.google-apps.folder', ...(parent ? { parents: [parent] } : {}) }; return drive('files?fields=id', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(meta) }).then(r => r.json()).then(x => x.id) }
export async function ensureRoots(): Promise<DriveRoots> { const root = await findOrCreateFolder('My Writing App'); const [journal, stories, attachments, versions, appData] = await Promise.all(['Journal', 'Stories', 'Attachments', 'Versions', 'AppData'].map(n => findOrCreateFolder(n, root))); return { root, journal, stories, attachments, versions, appData } }
export async function saveJson(name: string, data: unknown, parent: string, fileId?: string) { const meta = { name, mimeType: 'application/json', ...(fileId ? {} : { parents: [parent] }) }; const form = new FormData(); form.append('metadata', new Blob([JSON.stringify(meta)], { type: 'application/json' })); form.append('file', new Blob([JSON.stringify(data)], { type: 'application/json' }), name); const endpoint = fileId ? `https://www.googleapis.com/upload/drive/v3/files/${fileId}?uploadType=multipart&fields=id,modifiedTime` : 'https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,modifiedTime'; const r = await fetch(endpoint, { method: fileId ? 'PATCH' : 'POST', headers: { Authorization: `Bearer ${accessToken}` }, body: form }); if (!r.ok) throw new Error(`Drive upload failed (${r.status}): ${(await r.text()).slice(0, 180)}`); return r.json() as Promise<{ id: string; modifiedTime: string }> }
export async function saveBlob(name: string, blob: Blob, parent: string, fileId?: string) { const meta = { name, mimeType: blob.type || 'application/octet-stream', parents: [parent] }; const form = new FormData(); form.append('metadata', new Blob([JSON.stringify(meta)], { type: 'application/json' })); form.append('file', blob, name); const endpoint = fileId ? `https://www.googleapis.com/upload/drive/v3/files/${fileId}?uploadType=multipart&fields=id` : 'https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id'; const r = await fetch(endpoint, { method: fileId ? 'PATCH' : 'POST', headers: { Authorization: `Bearer ${accessToken}` }, body: form }); if (!r.ok) throw new Error(`Attachment upload failed (${r.status})`); return r.json() as Promise<{ id: string }> }
export async function listAppFiles(root: string) { return drive(`files?q=${encodeURIComponent(`'${root}' in parents and trashed=false`)}&fields=files(id,name,modifiedTime,mimeType)&pageSize=1000`).then(r => r.json()) }
export async function downloadJson(id: string) { return drive(`files/${id}?alt=media`).then(r => r.json()) }
