import { useEffect, useState } from 'react'
import { BookOpen, CalendarDays, ChevronRight, History, X } from 'lucide-react'
import { db } from '../db'
import { snapshot } from '../services/versions'
import type { Version, WritingDocument } from '../types'

const formatted = (value: string) => new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value))

export function HistoryBrowser({ docs }: { docs: WritingDocument[]; onOpen?: (doc: WritingDocument) => void }) {
  const [area, setArea] = useState<'journal' | 'stories'>('journal'); const [chosen, setChosen] = useState<WritingDocument>(); const [versions, setVersions] = useState<Version[]>([]); const [viewing, setViewing] = useState<Version>()
  const items = docs.filter(d => area === 'journal' ? d.type === 'journal' : d.type !== 'journal')
  useEffect(() => { setChosen(undefined); setVersions([]); setViewing(undefined) }, [area])
  useEffect(() => { if (chosen) void db.versions.where('documentId').equals(chosen.id).reverse().sortBy('timestamp').then(setVersions) }, [chosen])
  const restore = async () => { if (!chosen || !viewing) return; await snapshot(chosen, 'restore'); const next = { ...chosen, content: viewing.content, plainText: new DOMParser().parseFromString(viewing.content, 'text/html').body.innerText, updatedAt: new Date().toISOString(), syncState: 'pending' as const }; await db.documents.put(next); await snapshot(next, 'restore', true); setChosen(next); setViewing(undefined); setVersions(await db.versions.where('documentId').equals(chosen.id).reverse().sortBy('timestamp')) }
  if (!chosen) return <section className="page history-browser"><div className="page-heading"><div><p className="eyebrow">SAFE RECOVERY</p><h1>Version history</h1><p>Choose an area, then the writing you want to review.</p></div></div><div className="history-tabs"><button className={area === 'journal' ? 'active' : 'secondary'} onClick={() => setArea('journal')}><CalendarDays/>Journal</button><button className={area === 'stories' ? 'active' : 'secondary'} onClick={() => setArea('stories')}><BookOpen/>Stories & books</button></div><div className="history-documents">{items.map(doc => <button key={doc.id} className="history-document" onClick={() => setChosen(doc)}><span><strong>{doc.title}</strong><small>{doc.type}</small></span><ChevronRight/></button>)}</div></section>
  return <section className="page history-browser"><button className="back-button" onClick={() => setChosen(undefined)}>← Back to {area === 'journal' ? 'Journal' : 'Stories & books'}</button><div className="page-heading"><div><p className="eyebrow">EDIT LOG</p><h1>{chosen.title}</h1><p>Snapshots are immutable. Viewing one never opens or edits your current document.</p></div></div>{versions.length ? <div className="versions">{versions.map(v => <article key={v.id}><div><strong>{formatted(v.timestamp)}</strong><span>{v.reason === 'restore' ? 'Restored version' : 'Writing snapshot'}</span></div><button className="secondary small" onClick={() => setViewing(v)}>View version</button></article>)}</div> : <div className="empty"><History size={34}/><h2>No snapshots yet</h2><p>Future meaningful edits will appear here automatically.</p></div>}{viewing && <div className="modal-backdrop"><div className="modal"><button className="close" onClick={() => setViewing(undefined)}><X/></button><h2>{chosen.title}</h2><p className="muted">Read-only snapshot · {formatted(viewing.timestamp)}</p><article className="version-content" dangerouslySetInnerHTML={{ __html: viewing.content }}/><div className="row"><button className="secondary" onClick={() => setViewing(undefined)}>Close</button><button onClick={() => void restore()}>Restore as new version</button></div></div></div>}</section>
}
